name: Say Hello No 2

on:
    push:
        branches:
            - main

jobs:
    helloWorld:
        runs-on: ubuntu-latest

        steps:
            - name: Echo the message
              run: echo "Hola a todos"
            - name: dime la fecha
              run: date
            - run: ls-l





