name: deploy pipeline

on:
    push:
        branches:
            - main


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm install
            - name: Lint
              run: npm run eslint
            - name: Build
              run: npm run build
            - name: Tests
              run: npm test
              

